# Generated by Django 3.0 on 2020-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_wdt',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work_wdt',
            name='picture',
            field=models.ImageField(height_field='picture_height', null=True, upload_to='pictures/%Y/%m/%d', width_field='picture_width'),
        ),
        migrations.AlterField(
            model_name='work_cmt',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work_gdf',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
